### ISSUE TITLE
Greetings Juliano

### ISSUE THREAD

**Issue by ronancpl** [JulianoPeresLadeira/knights-tour#1]
Howdy Juliano, it's been a while since we last chatted, back then at CS grad school!

So cool that you've been able to keep the Knight's tour assignment, from Discrete Math, I also did! 😃

Lol that takes back, this very C assignment is one that I implemented the solution, with a twist, actually quite an embarrassing one 😓 in regards to common programming practices: my solution comprised of 1 file, and 1 main method, is all.

Take a look at it, should you have the time! 
[passeio_cavalo.zip](https://github.com/JulianoPeresLadeira/knights-tour/files/5792588/passeio_cavalo.zip)

**Comment by JulianoPeresLadeira** [comment]
Hey man! Long time no talk!

I was looking at this earlier today and I think the knight's tour is a nice project to revisit every now and then, not too big so as to get overwhelming nor too easy so as to be trivial. I was actually floored how much simpler my C solution ended up being compared to my typescript solution, guess I over engineered it quite a bit hehe. I think I'll take the time to write a solution for other programming languages, it's a good way to keep the tooling for the language fresh in the mind, and to get to work on something more complicated than sorting algorithms. Greatly recommend doing so!
